### ISSUE TITLE
CairoMakie has been moved into the monorepo at Makie.jl.

### ISSUE THREAD

**Issue by MrBenzWorld** [DanielVandH/FiniteVolumeMethod.jl#23]
Please fix this problem.
![error](https://user-images.githubusercontent.com/113277019/208927114-0c2833bc-d6fc-40eb-9595-d312adbb5b85.jpg)

**Comment by DanielVandH** [comment]
I'm not sure I follow what your image is showing here. Is it about me using `using CairoMakie` rather than `using Makie`? If so, I think that's fine:

> Add one or more of the Makie backend packages [GLMakie.jl](https://docs.makie.org/stable/documentation/backends/glmakie/) (OpenGL), [CairoMakie.jl](https://docs.makie.org/stable/documentation/backends/cairomakie/) (Cairo), or [WGLMakie.jl](https://docs.makie.org/stable/documentation/backends/wglmakie/) (WebGL), [RPRMakie](https://docs.makie.org/stable/documentation/backends/rprmakie/) (RadeonProRender) using Julia's inbuilt package manager. Each backend re-exports Makie so there's no need to install it separately.
