### ISSUE TITLE
Julia wrapper for SU2 (The Open-Source CFD Code) (Stanford University Unstructured)

### ISSUE THREAD

**Issue by MrBenzWorld** [DanielVandH/FiniteVolumeMethod.jl#24]
Python wrapper is available for SU2 (The Open-Source CFD Code).
Please provide Julia wrapper for SU2.
SU2 is a suite of open-source software tools written in C++ for the numerical solution of partial differential equations and performing PDE-constrained optimization.

There is no package for CFD in Julia. SU2 is good access for Julia.
could forward it to the correct group to get more attention. 
@DanielVandH 
@ablaom

**Comment by DanielVandH** [comment]
@MrBenzWorld 

This would be an interesting project, although not one I'd personally have the time to develop - nor the skills probably, I know next to nothing about C++. Currently the time that I do have for this package would be on e.g. #16.

Maybe one idea for you is to consider similar projects where people have wrapped similar software in Julia and see if you can use their approach for wrapping SU2 (e.g. with https://github.com/JuliaInterop/CxxWrap.jl? I don't know) into another package e.g. SU2.jl. That would be a nice contribution.
